# Generated by Django 6.0.2 on 2026-02-11 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_agentheartbeat_recording'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshotlog',
            name='captured_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='AgentToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='monitoring.agentsession')),
            ],
        ),
    ]
