# Generated by Django 6.0.2 on 2026-02-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_alter_screenshotlog_captured_at_agenttoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='ai_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recording',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recording',
            name='file_size_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recording',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recording',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('RECORDED', 'Recorded'), ('UPLOADING', 'Uploading'), ('UPLOADED', 'Uploaded'), ('FAILED', 'Failed')], default='CREATED', max_length=20),
        ),
        migrations.AddField(
            model_name='recording',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
