# Generated by Django 5.2.11 on 2026-02-17 08:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_recording_ai_processed_recording_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
