# Generated by Codex on 2026-02-19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0005_agenttoken_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIMetric",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_type", models.CharField(choices=[("screenshot", "Screenshot"), ("recording_window", "Recording Window")], max_length=32)),
                ("source_ref", models.CharField(max_length=1024)),
                ("ocr_text_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("feature_version", models.CharField(max_length=64)),
                ("features", models.JSONField(default=dict)),
                ("productivity_score", models.FloatField()),
                ("anomaly_score", models.FloatField()),
                ("anomaly_label", models.CharField(choices=[("normal", "Normal"), ("suspicious", "Suspicious"), ("critical", "Critical")], max_length=32)),
                ("model_info", models.JSONField(default=dict)),
                ("pipeline_status", models.CharField(choices=[("ok", "OK"), ("partial", "Partial"), ("failed", "Failed")], max_length=32)),
                ("error_code", models.CharField(blank=True, max_length=64, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("idempotency_key", models.CharField(max_length=64, unique=True)),
                ("agent_timestamp", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ai_metrics", to="monitoring.agentsession")),
            ],
        ),
    ]
