# Generated by Codex on 2026-02-19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0006_aimetric"),
    ]

    operations = [
        migrations.AlterField(
            model_name="screenshotlog",
            name="captured_at",
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name="screenshotlog",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="screenshotlog",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="screenshots/",
            ),
        ),
        migrations.RemoveField(
            model_name="screenshotlog",
            name="image_path",
        ),
    ]
