# Generated by Codex on 2026-02-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0007_align_screenshotlog_schema"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="aimetric",
            index=models.Index(
                fields=["session", "created_at"],
                name="monitoring__session_bd41f2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aimetric",
            index=models.Index(
                fields=["anomaly_label"],
                name="monitoring__anomaly_fa383b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aimetric",
            index=models.Index(
                fields=["created_at"],
                name="monitoring__created_97ee64_idx",
            ),
        ),
    ]
